


services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app_db



  adminer:
    image: adminer
    ports:
      - "8088:8080"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - pg

    ports:
      - "8001:8000"
    command: [ "sh", "-c", "alembic upgrade head && uvicorn main:main_app --host 0.0.0.0 --port 8000 --workers 4" ]



