"""писание миграции

Revision ID: 36b0ff74352c
Revises: 2e1ab68e9c95
Create Date: 2025-01-27 15:04:13.488793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36b0ff74352c"
down_revision: Union[str, None] = "2e1ab68e9c95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("orders", sa.Column("notified", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("orders", "notified")

    # ### end Alembic commands ###
